name: Flutter Action

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'
      
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.13.8'
      
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build apk --release --split-per-abi
      - run: flutter build appbundle

      - uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: 
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/apk/release/app-armeabi-v7a-release.apk
            build/app/outputs/bundle/release/app.aab
      
